name: Bug Report
description: Report something that is broken
title: "bug: "
labels: ["bug"]

body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: What did you expect vs what actually happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. 
        2. 
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: Browser, OS, bun version etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: Tested fix locally
        - label: Didn't break anything else
